version: '3.5' 

services: 

    front: 
      image: mlfrontend
      ports: 
        - 3000:3000

    back: 
      image: mlbackend
      volumes:
        - ./src/model:/src/model
      ports: 
        - 5000:5000
    
    training:
      image: mltraining
      volumes:
        - ./src/imgs:/src/imgs
        - ./src/model:/src/model
      container_name: mltraining
   
