version: '3.5' 

services: 

    simpleweb: 
      image: devopsdockeruh/simple-web-service 
      ports: 
        - 8080:8080
      build: . 
      volumes: 
        - ./text.log:/usr/src/app/text.log
      container_name: simpleweb
      command: server
