version: '3.5' 

services: 

    front: 
      image: frontend
      ports: 
        - 5000:5000


    back: 
      image: backend
      ports: 
        - 8080:8080
     
      
        

    redis: 
      image: redis
      container_name: redis_cache


      

    
     