version: '3.5' 

services: 

    front: 
      image: frontend
      ports: 
        - 5000:5000
      container_name: front


    back: 
      image: backend
      ports: 
        - 8080:8080
      container_name: back